FROM apache/iggy:latest

ENV 	IGGY_ROOT_USERNAME=iggy \
	IGGY_ROOT_PASSWORD=iggy \
	IGGY_TCP_ENABLED=true \
	IGGY_TCP_ADDRESS=0.0.0.0:8090 \
	IGGY_HTTP_ENABLED=true \
	IGGY_HTTP_ADDRESS=0.0.0.0:3000 \
	IGGY_QUIC_ENABLED=false \
	IGGY_WEBSOCKET_ENABLED=false

EXPOSE 8090
EXPOSE 3000
